<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Booking_page</name>
   <tag></tag>
   <elementGuidId>804eedc7-b038-4a88-82b5-880c4045911e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='proj-breadcrumb']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f28283e-5561-47b3-9771-94eda1458c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>proj-inlineblock</value>
      <webElementGuid>6ee84b3a-9974-40da-a189-125eaa3874c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home / Booking (step 1)</value>
      <webElementGuid>ca1b2dd1-4fbb-4a7e-a9fe-4a8025c7618a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proj-breadcrumb&quot;)/div[@class=&quot;proj-inlinecontainer&quot;]/div[@class=&quot;proj-inlineblock&quot;]</value>
      <webElementGuid>a3b01f64-6849-4897-9a24-48cc93f97df0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proj-breadcrumb']/div/div[2]</value>
      <webElementGuid>52d6532f-2907-4fa6-8d82-314bddd6b004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose a class'])[1]/preceding::div[3]</value>
      <webElementGuid>b8c77130-45a9-49e1-bddd-47016d261528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick available date'])[1]/preceding::div[6]</value>
      <webElementGuid>dde4d566-743e-4c07-a83b-bafe887b0cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/ Booking (step 1)']/parent::*</value>
      <webElementGuid>3ef62fe5-8fdb-48a3-b955-b60aa2142643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div[2]</value>
      <webElementGuid>f5c1a0be-159e-4d7d-833c-fd922ab21fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Home / Booking (step 1)' or . = 'Home / Booking (step 1)')]</value>
      <webElementGuid>dfb83d32-32c3-4b95-b0e3-69750cbf8d0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
